-- Standalone loadstring entry point generated by tools/build-bundle.mjs.

-- This chunk returns the Nebula API table without sibling-file dependencies.

local __factories = {}

__factories["Animation.Animator"] = function(require)

local TweenService = game:GetService("TweenService")
local Maid = require("Core.Maid")

local Animator = {}
Animator.__index = Animator

local presets = {
    surfaceIn = TweenInfo.new(0.32, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
    control = TweenInfo.new(0.18, Enum.EasingStyle.Quad, Enum.EasingDirection.Out),
    spring = TweenInfo.new(0.48, Enum.EasingStyle.Back, Enum.EasingDirection.Out),
    quick = TweenInfo.new(0.1, Enum.EasingStyle.Quad, Enum.EasingDirection.Out),
    reveal = TweenInfo.new(0.36, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
    orbit = TweenInfo.new(0.72, Enum.EasingStyle.Sine, Enum.EasingDirection.InOut),
}

function Animator.new(reducedMotion: boolean?)
    return setmetatable({
        _reducedMotion = reducedMotion == true,
        _maid = Maid.new(),
        _active = {},
        _destroyed = false,
    }, Animator)
end

function Animator:SetReducedMotion(enabled: boolean)
    self._reducedMotion = enabled
end

function Animator:Play(instance: Instance, properties: {[string]: any}, preset: string?, delayTime: number?)
    assert(not self._destroyed, "Cannot animate after Animator:Destroy()")
    assert(instance and instance.Parent, "Cannot animate a missing or destroyed Instance")
    local old = self._active[instance]
    if old then
        old:Cancel()
    end
    if self._reducedMotion then
        for key, value in pairs(properties) do
            (instance :: any)[key] = value
        end
        return nil
    end
    local info = presets[preset or "control"] or presets.control
    local delay = math.max(delayTime or 0, 0)
    if delay > 0 then
        info = TweenInfo.new(info.Time, info.EasingStyle, info.EasingDirection, info.RepeatCount, info.Reverses, delay)
    end
    local tween = TweenService:Create(instance, info, properties)
    self._active[instance] = tween
    self._maid:Give(tween.Completed:Connect(function()
        if self._active[instance] == tween then
            self._active[instance] = nil
        end
    end))
    tween:Play()
    return tween
end

function Animator:Fade(instance: Instance, transparency: number, preset: string?)
    return self:Play(instance, { BackgroundTransparency = transparency }, preset or "control")
end

function Animator:Scale(instance: GuiObject, scale: number, preset: string?)
    local value = instance:FindFirstChildOfClass("UIScale") or Instance.new("UIScale")
    value.Parent = instance
    return self:Play(value, { Scale = scale }, preset or "spring")
end

function Animator:Spring(instance: Instance, properties: {[string]: any})
    return self:Play(instance, properties, "spring")
end

function Animator:Slide(instance: GuiObject, position: UDim2, preset: string?)
    return self:Play(instance, { Position = position }, preset or "reveal")
end

function Animator:Rotate(instance: GuiObject, rotation: number, preset: string?)
    return self:Play(instance, { Rotation = rotation }, preset or "orbit")
end

function Animator:Stagger(instances: {Instance}, properties: {[string]: any}, preset: string?, interval: number?)
    local spacing = math.max(interval or 0.06, 0)
    local tweens = {}
    for index, instance in ipairs(instances) do
        local tween = self:Play(instance, properties, preset or "surfaceIn", (index - 1) * spacing)
        if tween then
            table.insert(tweens, tween)
        end
    end
    return tweens
end

function Animator:GetActiveCount(): number
    local count = 0
    for _ in pairs(self._active) do
        count += 1
    end
    return count
end

function Animator:Destroy()
    if self._destroyed then
        return
    end
    self._destroyed = true
    for _, tween in pairs(self._active) do
        tween:Cancel()
    end
    table.clear(self._active)
    self._maid:Destroy()
end

return Animator

end

__factories["Components.Command"] = function(require)

local UserInputService = game:GetService("UserInputService")
local Component = require("Components.Component")

local Command = {}
Command.__index = Command

function Command.new(root: Instance, commands, theme, animations, maid)
    local overlay = Instance.new("Frame")
    overlay.Name = "NebulaCommand"
    overlay.BackgroundColor3 = theme.Background
    overlay.BackgroundTransparency = 0.05
    overlay.Size = UDim2.fromOffset(480, 340)
    overlay.AnchorPoint = Vector2.new(0.5, 0)
    overlay.Position = UDim2.new(0.5, 0, 0, 80)
    overlay.Visible = false
    overlay.Parent = root
    local corner = Instance.new("UICorner")
    corner.CornerRadius = UDim.new(0, theme.CornerRadius)
    corner.Parent = overlay
    local input = Instance.new("TextBox")
    input.ClearTextOnFocus = false
    input.PlaceholderText = "Search commands..."
    input.Text = ""
    input.TextColor3 = theme.Text
    input.PlaceholderColor3 = theme.TextMuted
    input.Font = Enum.Font.Gotham
    input.TextSize = 14
    input.BackgroundColor3 = theme.Surface
    input.BorderSizePixel = 0
    input.Position = UDim2.fromOffset(12, 12)
    input.Size = UDim2.new(1, -24, 0, 42)
    input.Parent = overlay
    local list = Instance.new("ScrollingFrame")
    list.BackgroundTransparency = 1
    list.BorderSizePixel = 0
    list.Position = UDim2.fromOffset(12, 66)
    list.Size = UDim2.new(1, -24, 1, -78)
    list.AutomaticCanvasSize = Enum.AutomaticSize.Y
    list.CanvasSize = UDim2.new()
    list.ScrollBarThickness = 2
    list.Parent = overlay
    local layout = Instance.new("UIListLayout")
    layout.Padding = UDim.new(0, 4)
    layout.Parent = list

    local self = Component.new(overlay, theme, animations)
    setmetatable(self, Command)
    self._input = input
    self._list = list
    self._commands = commands or {}
    self._root = root
    self._render = function()
        for _, child in ipairs(list:GetChildren()) do
            if child:IsA("TextButton") then child:Destroy() end
        end
        local query = input.Text:lower()
        for _, item in ipairs(self._commands) do
            if query == "" or item.Label:lower():find(query, 1, true) then
                local button = Instance.new("TextButton")
                button.BackgroundColor3 = theme.SurfaceSecondary
                button.BorderSizePixel = 0
                button.Size = UDim2.new(1, 0, 0, 34)
                button.Font = Enum.Font.Gotham
                button.Text = item.Label
                button.TextColor3 = theme.TextSecondary
                button.TextSize = 12
                button.TextXAlignment = Enum.TextXAlignment.Left
                button.Parent = list
                local p = Instance.new("UIPadding")
                p.PaddingLeft = UDim.new(0, 12)
                p.Parent = button
                button.Activated:Connect(function()
                    item.OnSelect()
                    self:Close()
                end)
            end
        end
    end
    self.Maid:Give(input:GetPropertyChangedSignal("Text"):Connect(self._render))
    self.Maid:Give(UserInputService.InputBegan:Connect(function(inputObject, processed)
        if processed then return end
        if inputObject.KeyCode == Enum.KeyCode.P then
            self:Toggle()
        elseif inputObject.KeyCode == Enum.KeyCode.Escape then
            self:Close()
        end
    end))
    maid:Give(self)
    self._render()
    return self
end

function Command:Toggle()
    if self.Instance.Visible then self:Close() else self:Open() end
end

function Command:Open()
    self.Instance.Visible = true
    self._input:CaptureFocus()
end

function Command:Close()
    self.Instance.Visible = false
    self._input:ReleaseFocus()
end

return Command

end

__factories["Components.Component"] = function(require)

local Maid = require("Core.Maid")

local Component = {}
Component.__index = Component

function Component.new(instance: GuiObject, theme, animations)
    return setmetatable({
        Instance = instance,
        Theme = theme,
        Animations = animations,
        Maid = Maid.new(),
        _destroyed = false,
    }, Component)
end

function Component:IsAlive(): boolean
    return not self._destroyed and self.Instance.Parent ~= nil
end

function Component:Destroy()
    if self._destroyed then
        return
    end
    self._destroyed = true
    self.Maid:Destroy()
    if self.Instance.Parent then
        self.Instance:Destroy()
    end
end

return Component

end

__factories["Components.Controls.Button"] = function(require)

local Component = require("Components.Component")

local Button = {}
Button.__index = Button

function Button.new(parent: Instance, options: {[string]: any}, theme, animations)
    local button = Instance.new("TextButton")
    button.Name = options.Label or "Button"
    button.AutoButtonColor = false
    button.BackgroundColor3 = theme.SurfaceSecondary
    button.BorderSizePixel = 0
    button.Size = UDim2.new(1, 0, 0, theme.ControlHeight)
    button.Font = Enum.Font.GothamMedium
    button.Text = options.Label or "Button"
    button.TextColor3 = theme.Text
    button.TextSize = 13
    button.Parent = parent
    local scale = Instance.new("UIScale")
    scale.Scale = 0.96
    scale.Parent = button
    local corner = Instance.new("UICorner")
    corner.CornerRadius = UDim.new(0, theme.CornerRadius - 3)
    corner.Parent = button
    local self = Component.new(button, theme, animations)
    setmetatable(self, Button)
    animations:Scale(button, 1, "spring")

    self.Maid:Give(button.MouseEnter:Connect(function()
        animations:Play(button, { BackgroundColor3 = theme.Border }, "quick")
        animations:Scale(button, 1.025, "quick")
    end))
    self.Maid:Give(button.MouseLeave:Connect(function()
        animations:Play(button, { BackgroundColor3 = theme.SurfaceSecondary }, "quick")
        animations:Scale(button, 1, "quick")
    end))
    self.Maid:Give(button.Activated:Connect(function()
        if options.OnClick then
            options.OnClick()
        end
    end))
    return self
end

return Button

end

__factories["Components.Controls.Slider"] = function(require)

local UserInputService = game:GetService("UserInputService")
local Component = require("Components.Component")
local Value = require("State.Value")

local Slider = {}
Slider.__index = Slider

function Slider.new(parent: Instance, options: {[string]: any}, theme, animations)
    local min = options.Min or 0
    local max = options.Max or 100
    local value = math.clamp(options.Default or min, min, max)
    local holder = Instance.new("Frame")
    holder.Name = options.Label or "Slider"
    holder.BackgroundTransparency = 1
    holder.Size = UDim2.new(1, 0, 0, 54)
    holder.Parent = parent

    local label = Instance.new("TextLabel")
    label.BackgroundTransparency = 1
    label.Size = UDim2.new(0.7, 0, 0, 20)
    label.Font = Enum.Font.Gotham
    label.Text = options.Label or "Slider"
    label.TextColor3 = theme.TextSecondary
    label.TextSize = 13
    label.TextXAlignment = Enum.TextXAlignment.Left
    label.Parent = holder
    local readout = label:Clone()
    readout.Name = "Value"
    readout.Position = UDim2.new(0.7, 0, 0, 0)
    readout.Size = UDim2.new(0.3, 0, 0, 20)
    readout.Text = tostring(value)
    readout.TextXAlignment = Enum.TextXAlignment.Right
    readout.Parent = holder

    local rail = Instance.new("Frame")
    rail.AnchorPoint = Vector2.new(0, 0.5)
    rail.Position = UDim2.new(0, 0, 0, 38)
    rail.Size = UDim2.new(1, 0, 0, 6)
    rail.BackgroundColor3 = theme.Border
    rail.BorderSizePixel = 0
    rail.Parent = holder
    local railCorner = Instance.new("UICorner")
    railCorner.CornerRadius = UDim.new(1, 0)
    railCorner.Parent = rail
    local fill = rail:Clone()
    fill.Name = "Fill"
    fill.BackgroundColor3 = theme.Accent
    fill.Size = UDim2.new((value - min) / math.max(max - min, 1), 0, 1, 0)
    fill.Parent = rail
    local knob = Instance.new("TextButton")
    knob.Name = "Knob"
    knob.Text = ""
    knob.AutoButtonColor = false
    knob.AnchorPoint = Vector2.new(0.5, 0.5)
    knob.Position = UDim2.new((value - min) / math.max(max - min, 1), 0, 0.5, 0)
    knob.Size = UDim2.fromOffset(18, 18)
    knob.BackgroundColor3 = theme.Text
    knob.BorderSizePixel = 0
    knob.Parent = rail
    local knobCorner = Instance.new("UICorner")
    knobCorner.CornerRadius = UDim.new(1, 0)
    knobCorner.Parent = knob

    local self = Component.new(holder, theme, animations)
    setmetatable(self, Slider)
    self.Min = min
    self.Max = max
    self.Value = Value.new(value)
    local dragging = false
    local function update(inputX: number)
        local ratio = math.clamp((inputX - rail.AbsolutePosition.X) / rail.AbsoluteSize.X, 0, 1)
        self:Set(min + (max - min) * ratio)
    end
    local function render(nextValue: number)
        local ratio = (nextValue - min) / math.max(max - min, 1)
        readout.Text = options.Format and options.Format(nextValue) or tostring(math.floor(nextValue * 100) / 100)
        animations:Play(fill, { Size = UDim2.new(ratio, 0, 1, 0) }, "quick")
        animations:Play(knob, { Position = UDim2.new(ratio, 0, 0.5, 0) }, "quick")
    end
    self.Maid:Give(self.Value:Subscribe(function(nextValue)
        render(nextValue)
        if options.OnChanged then
            options.OnChanged(nextValue)
        end
    end))
    self.Maid:Give(knob.InputBegan:Connect(function(input)
        if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then
            dragging = true
        end
    end))
    self.Maid:Give(UserInputService.InputChanged:Connect(function(input)
        if dragging and (input.UserInputType == Enum.UserInputType.MouseMovement or input.UserInputType == Enum.UserInputType.Touch) then
            update(input.Position.X)
        end
    end))
    self.Maid:Give(UserInputService.InputEnded:Connect(function(input)
        if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then
            dragging = false
        end
    end))
    self.Maid:Give(self.Value)
    return self
end

function Slider:Get(): number
    return self.Value:Get()
end

function Slider:Set(value: number)
    self.Value:Set(math.clamp(value, self.Min or -math.huge, self.Max or math.huge))
end

function Slider:OnChanged(callback: (number) -> ()): RBXScriptConnection
    return self.Value:Subscribe(callback)
end

return Slider

end

__factories["Components.Controls.Toggle"] = function(require)

local Component = require("Components.Component")
local Value = require("State.Value")

local Toggle = {}
Toggle.__index = Toggle

function Toggle.new(parent: Instance, options: {[string]: any}, theme, animations)
    local row = Instance.new("TextButton")
    row.Name = options.Label or "Toggle"
    row.AutoButtonColor = false
    row.BackgroundTransparency = 1
    row.Size = UDim2.new(1, 0, 0, theme.ControlHeight)
    row.Text = ""
    row.Parent = parent

    local label = Instance.new("TextLabel")
    label.BackgroundTransparency = 1
    label.Size = UDim2.new(1, -58, 1, 0)
    label.Font = Enum.Font.Gotham
    label.Text = options.Label or "Toggle"
    label.TextColor3 = theme.TextSecondary
    label.TextSize = 13
    label.TextXAlignment = Enum.TextXAlignment.Left
    label.Parent = row

    local track = Instance.new("Frame")
    track.AnchorPoint = Vector2.new(1, 0.5)
    track.Position = UDim2.new(1, 0, 0.5, 0)
    track.Size = UDim2.fromOffset(42, 22)
    track.BackgroundColor3 = theme.Border
    track.BorderSizePixel = 0
    track.Parent = row
    local trackCorner = Instance.new("UICorner")
    trackCorner.CornerRadius = UDim.new(1, 0)
    trackCorner.Parent = track
    local knob = Instance.new("Frame")
    knob.Size = UDim2.fromOffset(16, 16)
    knob.Position = UDim2.fromOffset(3, 3)
    knob.BackgroundColor3 = theme.Text
    knob.BorderSizePixel = 0
    knob.Parent = track
    local knobCorner = Instance.new("UICorner")
    knobCorner.CornerRadius = UDim.new(1, 0)
    knobCorner.Parent = knob

    local self = Component.new(row, theme, animations)
    setmetatable(self, Toggle)
    self.Value = Value.new(options.Default == true)

    local function render(value: boolean)
        animations:Play(track, { BackgroundColor3 = value and theme.Accent or theme.Border }, "quick")
        animations:Play(knob, { Position = value and UDim2.fromOffset(23, 3) or UDim2.fromOffset(3, 3) }, "quick")
    end
    render(self.Value:Get())
    self.Maid:Give(self.Value:Subscribe(function(value)
        render(value)
        if options.OnChanged then
            options.OnChanged(value)
        end
    end))
    self.Maid:Give(row.Activated:Connect(function()
        self:Set(not self:Get())
    end))
    self.Maid:Give(self.Value)
    return self
end

function Toggle:Get(): boolean
    return self.Value:Get()
end

function Toggle:Set(value: boolean)
    self.Value:Set(value == true)
end

function Toggle:OnChanged(callback: (boolean) -> ()): RBXScriptConnection
    return self.Value:Subscribe(callback)
end

return Toggle

end

__factories["Components.Surface"] = function(require)

local Component = require("Components.Component")
local Layout = require("Layout.Layout")

local Surface = {}
Surface.__index = Surface
setmetatable(Surface, Component)

function Surface.new(parent: Instance, options: {[string]: any}, theme, animations)
    local frame = Instance.new("Frame")
    frame.Name = options.Title or "Surface"
    frame.BackgroundColor3 = theme.Surface
    frame.BackgroundTransparency = theme.Transparency
    frame.BorderSizePixel = 0
    frame.Size = options.Size or UDim2.new(1, 0, 0, 160)
    frame.LayoutOrder = options.LayoutOrder or 0
    frame.Parent = parent

    local corner = Instance.new("UICorner")
    corner.CornerRadius = UDim.new(0, options.CornerRadius or theme.CornerRadius)
    corner.Parent = frame

    local stroke = Instance.new("UIStroke")
    stroke.Color = theme.Border
    stroke.Transparency = 0.2
    stroke.Parent = frame

    local self = Component.new(frame, theme, animations)
    setmetatable(self, Surface)
    self.Content = Instance.new("Frame")
    self.Content.Name = "Content"
    self.Content.BackgroundTransparency = 1
    self.Content.Position = UDim2.fromOffset(16, options.Title and 46 or 16)
    self.Content.Size = UDim2.new(1, -32, 1, options.Title and -62 or -32)
    self.Content.Parent = frame
    Layout.Column(self.Content, { Spacing = 8 })

    if options.Title then
        local title = Instance.new("TextLabel")
        title.Name = "Title"
        title.BackgroundTransparency = 1
        title.Position = UDim2.fromOffset(16, 13)
        title.Size = UDim2.new(1, -32, 0, 22)
        title.Font = Enum.Font.GothamMedium
        title.Text = options.Title
        title.TextColor3 = theme.Text
        title.TextSize = 15
        title.TextXAlignment = Enum.TextXAlignment.Left
        title.Parent = frame
    end
    return self
end

function Surface:AddButton(options: {[string]: any})
    local Button = require("Components.Controls.Button")
    local button = Button.new(self.Content, options, self.Theme, self.Animations)
    self.Maid:Give(button)
    return button
end

function Surface:AddToggle(options: {[string]: any})
    local Toggle = require("Components.Controls.Toggle")
    local toggle = Toggle.new(self.Content, options, self.Theme, self.Animations)
    self.Maid:Give(toggle)
    return toggle
end

function Surface:AddSlider(options: {[string]: any})
    local Slider = require("Components.Controls.Slider")
    local slider = Slider.new(self.Content, options, self.Theme, self.Animations)
    self.Maid:Give(slider)
    return slider
end

return Surface

end

__factories["Components.Tab"] = function(require)

local Surface = require("Components.Surface")

local Tab = {}
Tab.__index = Tab

function Tab:AddSurface(options: {[string]: any})
    local surface = Surface.new(self.Page, options or {}, self._window.Theme, self._window.Animations)
    self.Maid:Give(surface)
    return surface
end

function Tab:AddText(text: string, options: {[string]: any}?)
    local label = Instance.new("TextLabel")
    label.BackgroundTransparency = 1
    label.Size = UDim2.new(1, 0, 0, options and options.Height or 24)
    label.Font = options and options.Font or Enum.Font.Gotham
    label.Text = text
    label.TextColor3 = options and options.Color or self._window.Theme.TextSecondary
    label.TextSize = options and options.TextSize or 13
    label.TextWrapped = true
    label.TextXAlignment = Enum.TextXAlignment.Left
    label.Parent = self.Page
    self.Maid:Give(label)
    return label
end

function Tab:Destroy()
    self.Maid:Destroy()
end

return Tab

end

__factories["Components.ToastStack"] = function(require)

local Component = require("Components.Component")

local ToastStack = {}
ToastStack.__index = ToastStack

function ToastStack.new(root: Instance, theme, animations, maid)
    local holder = Instance.new("Frame")
    holder.Name = "NebulaToastStack"
    holder.BackgroundTransparency = 1
    holder.AnchorPoint = Vector2.new(1, 1)
    holder.Position = UDim2.new(1, -24, 1, -24)
    holder.Size = UDim2.fromOffset(300, 240)
    holder.Parent = root
    local layout = Instance.new("UIListLayout")
    layout.VerticalAlignment = Enum.VerticalAlignment.Bottom
    layout.HorizontalAlignment = Enum.HorizontalAlignment.Right
    layout.Padding = UDim.new(0, 8)
    layout.Parent = holder
    local self = Component.new(holder, theme, animations)
    setmetatable(self, ToastStack)
    maid:Give(self)
    return self
end

function ToastStack:Push(message: string, kind: string?, duration: number?)
    local colors = {
        success = self.Theme.Success,
        warning = self.Theme.Warning,
        error = self.Theme.Error,
        info = self.Theme.Info,
    }
    local toast = Instance.new("TextLabel")
    toast.BackgroundColor3 = self.Theme.Surface
    toast.BackgroundTransparency = self.Theme.Transparency
    toast.BorderSizePixel = 0
    toast.Size = UDim2.fromOffset(280, 42)
    toast.Font = Enum.Font.GothamMedium
    toast.Text = message
    toast.TextColor3 = self.Theme.Text
    toast.TextSize = 12
    toast.TextWrapped = true
    toast.Parent = self.Instance
    local stroke = Instance.new("UIStroke")
    stroke.Color = colors[kind or "info"] or self.Theme.Accent
    stroke.Parent = toast
    local corner = Instance.new("UICorner")
    corner.CornerRadius = UDim.new(0, 9)
    corner.Parent = toast
    self.Animations:Scale(toast, 1, "spring")
    task.delay(duration or 3.5, function()
        if toast.Parent then
            self.Animations:Fade(toast, 1, "quick")
            task.delay(0.2, function()
                if toast.Parent then toast:Destroy() end
            end)
        end
    end)
    return toast
end

return ToastStack

end

__factories["Components.Window"] = function(require)

local UserInputService = game:GetService("UserInputService")
local Component = require("Components.Component")
local Surface = require("Components.Surface")
local Layout = require("Layout.Layout")

local Window = {}
Window.__index = Window

function Window.new(root: Instance, options: {[string]: any}, theme, animations, maid)
    local frame = Instance.new("Frame")
    frame.Name = "NebulaWindow"
    frame.AnchorPoint = Vector2.new(0.5, 0.5)
    local targetPosition = UDim2.fromScale(0.5, 0.5)
    frame.Position = UDim2.new(0.5, 0, 0.5, 12)
    frame.Size = UDim2.fromOffset(820, 520)
    frame.BackgroundColor3 = theme.BackgroundSecondary
    frame.BackgroundTransparency = 1
    frame.BorderSizePixel = 0
    frame.Parent = root
    animations:Play(frame, {
        Position = targetPosition,
        BackgroundTransparency = 0.04,
    }, "reveal")
    local corner = Instance.new("UICorner")
    corner.CornerRadius = UDim.new(0, theme.CornerRadius + 4)
    corner.Parent = frame
    local stroke = Instance.new("UIStroke")
    stroke.Color = theme.Border
    stroke.Transparency = 0.12
    stroke.Parent = frame

    local header = Instance.new("Frame")
    header.BackgroundTransparency = 1
    header.Position = UDim2.fromOffset(20, 16)
    header.Size = UDim2.new(1, -40, 0, 42)
    header.Parent = frame
    local title = Instance.new("TextLabel")
    title.BackgroundTransparency = 1
    title.Size = UDim2.new(1, 0, 0, 22)
    title.Font = Enum.Font.GothamBold
    title.Text = options.Title or "Nebula"
    title.TextColor3 = theme.Text
    title.TextSize = 18
    title.TextXAlignment = Enum.TextXAlignment.Left
    title.Parent = header
    local subtitle = Instance.new("TextLabel")
    subtitle.BackgroundTransparency = 1
    subtitle.Position = UDim2.fromOffset(0, 23)
    subtitle.Size = UDim2.new(1, 0, 0, 16)
    subtitle.Font = Enum.Font.Gotham
    subtitle.Text = options.Subtitle or "Interface runtime"
    subtitle.TextColor3 = theme.TextMuted
    subtitle.TextSize = 11
    subtitle.TextXAlignment = Enum.TextXAlignment.Left
    subtitle.Parent = header

    local nav = Instance.new("Frame")
    nav.Name = "Navigation"
    nav.BackgroundTransparency = 1
    nav.Position = UDim2.fromOffset(20, 78)
    nav.Size = UDim2.new(0, 164, 1, -98)
    nav.Parent = frame
    Layout.Column(nav, { Spacing = 6 })
    local content = Instance.new("ScrollingFrame")
    content.Name = "Content"
    content.Position = UDim2.fromOffset(204, 78)
    content.Size = UDim2.new(1, -224, 1, -98)
    content.BackgroundTransparency = 1
    content.BorderSizePixel = 0
    content.ScrollBarThickness = 3
    content.ScrollBarImageColor3 = theme.Accent
    content.AutomaticCanvasSize = Enum.AutomaticSize.Y
    content.CanvasSize = UDim2.new()
    content.Parent = frame

    local self = Component.new(frame, theme, animations)
    setmetatable(self, Window)
    self._navigation = nav
    self._content = content
    self._tabs = {}
    self._active = nil
    maid:Give(self)

    local dragging = false
    local dragStart: Vector2
    local startPosition: UDim2
    self.Maid:Give(header.InputBegan:Connect(function(input)
        if input.UserInputType == Enum.UserInputType.MouseButton1 then
            dragging = true
            dragStart = input.Position
            startPosition = frame.Position
        end
    end))
    self.Maid:Give(UserInputService.InputChanged:Connect(function(input)
        if dragging and input.UserInputType == Enum.UserInputType.MouseMovement then
            local delta = input.Position - dragStart
            frame.Position = UDim2.new(startPosition.X.Scale, startPosition.X.Offset + delta.X, startPosition.Y.Scale, startPosition.Y.Offset + delta.Y)
        end
    end))
    self.Maid:Give(UserInputService.InputEnded:Connect(function(input)
        if input.UserInputType == Enum.UserInputType.MouseButton1 then
            dragging = false
        end
    end))
    return self
end

function Window:AddTab(name: string, icon: string?)
    local tabButton = Instance.new("TextButton")
    tabButton.Name = name
    tabButton.AutoButtonColor = false
    tabButton.BackgroundColor3 = self.Theme.SurfaceSecondary
    tabButton.BackgroundTransparency = 0.4
    tabButton.Size = UDim2.new(1, 0, 0, 34)
    tabButton.Font = Enum.Font.GothamMedium
    tabButton.Text = (icon and icon .. "  " or "") .. name
    tabButton.TextColor3 = self.Theme.TextSecondary
    tabButton.TextSize = 12
    tabButton.TextXAlignment = Enum.TextXAlignment.Left
    tabButton.Parent = self._navigation
    local padding = Instance.new("UIPadding")
    padding.PaddingLeft = UDim.new(0, 12)
    padding.Parent = tabButton
    local corner = Instance.new("UICorner")
    corner.CornerRadius = UDim.new(0, 8)
    corner.Parent = tabButton

    local page = Instance.new("Frame")
    page.Name = name .. "Page"
    page.BackgroundTransparency = 1
    page.Size = UDim2.new(1, -16, 0, 0)
    page.AutomaticSize = Enum.AutomaticSize.Y
    page.Visible = false
    page.Parent = self._content
    Layout.Column(page, { Spacing = 12 })
    local tab = setmetatable({
        Name = name,
        Page = page,
        Button = tabButton,
        _window = self,
        Maid = require("Core.Maid").new(),
    }, { __index = require("Components.Tab") })
    table.insert(self._tabs, tab)
    self.Maid:Give(tab)
    self.Maid:Give(tabButton.Activated:Connect(function()
        self:SelectTab(tab)
    end))
    if not self._active then
        self:SelectTab(tab)
    end
    return tab
end

function Window:SelectTab(tab)
    self._active = tab
    for _, item in ipairs(self._tabs) do
        local active = item == tab
        item.Page.Visible = active
        item.Button.BackgroundTransparency = active and 0 or 0.4
        item.Button.BackgroundColor3 = active and self.Theme.Accent or self.Theme.SurfaceSecondary
        item.Button.TextColor3 = active and self.Theme.Background or self.Theme.TextSecondary
        if active then
            local scale = item.Page:FindFirstChildOfClass("UIScale") or Instance.new("UIScale")
            scale.Scale = 0.97
            scale.Parent = item.Page
            self.Animations:Scale(item.Page, 1, "reveal")
        end
    end
end

return Window

end

__factories["Core.Maid"] = function(require)

local Maid = {}
Maid.__index = Maid
type Task = RBXScriptConnection | Instance | thread | (() -> ())

function Maid.new()
    return setmetatable({
        _tasks = {},
        _destroyed = false,
    }, Maid)
end

function Maid:Give(task: Task): Task
    assert(not self._destroyed, "Nebula Maid is already destroyed")
    table.insert(self._tasks, task)
    return task
end

function Maid:GiveConnection(connection: RBXScriptConnection): RBXScriptConnection
    return self:Give(connection)
end

local function cleanup(item: Task)
    local kind = typeof(item)
    if kind == "RBXScriptConnection" then
        (item :: RBXScriptConnection):Disconnect()
    elseif kind == "Instance" then
        (item :: Instance):Destroy()
    elseif kind == "thread" then
        task.cancel(item :: thread)
    elseif type(item) == "function" then
        (item :: () -> ())()
    elseif type(item) == "table" then
        local object = item :: any
        if type(object.Disconnect) == "function" then
            object:Disconnect()
        elseif type(object.Destroy) == "function" then
            object:Destroy()
        end
    end
end

function Maid:Cleanup()
    for index = #self._tasks, 1, -1 do
        local task = self._tasks[index]
        self._tasks[index] = nil
        cleanup(task)
    end
end

function Maid:Destroy()
    if self._destroyed then
        return
    end
    self._destroyed = true
    self:Cleanup()
end

return Maid

end

__factories["Core.Signal"] = function(require)

local Signal = {}
Signal.__index = Signal

function Signal.new()
    return setmetatable({
        _listeners = {},
        _destroyed = false,
    }, Signal)
end

function Signal:Connect(callback: (...any) -> ()): RBXScriptConnection
    assert(not self._destroyed, "Cannot connect to a destroyed Nebula Signal")
    local listeners = self._listeners
    local active = true
    local connection = {
        Disconnect = function()
            active = false
            listeners[callback] = nil
        end,
    }
    listeners[callback] = function(...)
        if active then
            callback(...)
        end
    end
    return connection :: any
end

function Signal:Fire(...)
    if self._destroyed then
        return
    end
    for _, callback in pairs(self._listeners) do
        task.spawn(callback, ...)
    end
end

function Signal:Destroy()
    self._destroyed = true
    table.clear(self._listeners)
end

return Signal

end

__factories["Layout.Layout"] = function(require)

local Layout = {}

local function addPadding(parent: Instance, padding: number?)
    if not padding then
        return
    end
    local value = Instance.new("UIPadding")
    value.PaddingTop = UDim.new(0, padding)
    value.PaddingBottom = UDim.new(0, padding)
    value.PaddingLeft = UDim.new(0, padding)
    value.PaddingRight = UDim.new(0, padding)
    value.Parent = parent
end

function Layout.Row(parent: Instance, options: {[string]: any}?)
    local layout = Instance.new("UIListLayout")
    layout.FillDirection = Enum.FillDirection.Horizontal
    layout.HorizontalAlignment = options and options.Alignment or Enum.HorizontalAlignment.Left
    layout.VerticalAlignment = options and options.VerticalAlignment or Enum.VerticalAlignment.Center
    layout.Padding = UDim.new(0, options and options.Spacing or 8)
    layout.Wraps = options and options.Wrap == true
    layout.Parent = parent
    addPadding(parent, options and options.Padding)
    return layout
end

function Layout.Column(parent: Instance, options: {[string]: any}?)
    local layout = Instance.new("UIListLayout")
    layout.FillDirection = Enum.FillDirection.Vertical
    layout.HorizontalAlignment = options and options.Alignment or Enum.HorizontalAlignment.Left
    layout.VerticalAlignment = options and options.VerticalAlignment or Enum.VerticalAlignment.Top
    layout.Padding = UDim.new(0, options and options.Spacing or 8)
    layout.Parent = parent
    addPadding(parent, options and options.Padding)
    return layout
end

function Layout.Grid(parent: Instance, options: {[string]: any}?)
    local layout = Instance.new("UIGridLayout")
    layout.CellSize = options and options.CellSize or UDim2.fromOffset(160, 100)
    layout.CellPadding = options and options.Spacing or UDim2.fromOffset(8, 8)
    layout.HorizontalAlignment = options and options.Alignment or Enum.HorizontalAlignment.Left
    layout.Parent = parent
    addPadding(parent, options and options.Padding)
    return layout
end

function Layout.Stack(parent: Instance)
    local layout = Instance.new("UIListLayout")
    layout.FillDirection = Enum.FillDirection.Vertical
    layout.SortOrder = Enum.SortOrder.LayoutOrder
    layout.Parent = parent
    return layout
end

function Layout.Overlay(parent: Instance)
    local container = Instance.new("Frame")
    container.Name = "Overlay"
    container.BackgroundTransparency = 1
    container.Size = UDim2.fromScale(1, 1)
    container.Parent = parent
    return container
end

return Layout

end

__factories["NebulaCore"] = function(require)

local Players = game:GetService("Players")
local RunService = game:GetService("RunService")

local Maid = require("Core.Maid")
local Manager = require("Theme.Manager")
local Animator = require("Animation.Animator")
local Root = require("Rendering.Root")
local Window = require("Components.Window")
local Command = require("Components.Command")
local ToastStack = require("Components.ToastStack")
local Responsive = require("Utilities.Responsive")

local Nebula = {}
Nebula.__index = Nebula

function Nebula.new(options: {[string]: any}?)
    options = options or {}
    local playerGui = options.Parent or Players.LocalPlayer:WaitForChild("PlayerGui")
    local self = setmetatable({
        Maid = Maid.new(),
        Debug = options.Debug == true,
        _componentCount = 0,
        _destroyed = false,
    }, Nebula)
    self.ThemeManager = Manager.new(options.Theme)
    self.Animations = Animator.new(options.ReducedMotion)
    self.Maid:Give(self.ThemeManager)
    self.Maid:Give(self.Animations)
    self.Root = Root.new(options.RenderMode or "2D", {
        Parent = playerGui,
        Adornee = options.Adornee,
        Face = options.Face,
        PixelsPerStud = options.PixelsPerStud,
        DisplayOrder = options.DisplayOrder,
    }, self.Maid)
    self._root = self.Root.Instance
    self.Toasts = ToastStack.new(self._root, self:GetTheme(), self.Animations, self.Maid)
    self.Commands = Command.new(self._root, options.Commands, self:GetTheme(), self.Animations, self.Maid)
    self.Maid:Give(self.ThemeManager:OnChanged(function(theme)
        self:_applyTheme(theme)
    end))
    self.Maid:Give(workspace.CurrentCamera:GetPropertyChangedSignal("ViewportSize"):Connect(function()
        self._breakpoint = Responsive.GetBreakpoint(workspace.CurrentCamera.ViewportSize.X)
        self:_applyResponsive()
    end))
    self._breakpoint = Responsive.GetBreakpoint(workspace.CurrentCamera.ViewportSize.X)
    self._applyResponsive()
    return self
end

function Nebula:CreateWindow(options: {[string]: any}?)
    assert(not self._destroyed, "Cannot create a window after Nebula:Destroy()")
    local window = Window.new(self._root, options or {}, self:GetTheme(), self.Animations, self.Maid)
    self._componentCount += 1
    return window
end

function Nebula:RegisterTheme(name: string, theme: {[string]: any})
    self.ThemeManager:Register(name, theme)
end

function Nebula:SetTheme(name: string)
    self.ThemeManager:Set(name)
end

function Nebula:GetTheme(): {[string]: any}
    return self.ThemeManager:Get()
end

function Nebula:ModifyTheme(changes: {[string]: any})
    self.ThemeManager:Modify(changes)
end

function Nebula:ResetTheme()
    self.ThemeManager:Reset()
end

function Nebula:SetRenderMode(mode: string, options: {[string]: any}?)
    self.Root:SetMode(mode, options)
    self._root = self.Root.Instance
end

function Nebula:SetDebug(enabled: boolean)
    self.Debug = enabled
end

function Nebula:SetReducedMotion(enabled: boolean)
    self.Animations:SetReducedMotion(enabled)
end

function Nebula:Toast(message: string, kind: string?, duration: number?)
    return self.Toasts:Push(message, kind, duration)
end

function Nebula:GetDiagnostics()
    local camera = workspace.CurrentCamera
    return {
        ComponentCount = self._componentCount,
        RenderMode = self.Root.Mode,
        Viewport = camera and camera.ViewportSize or Vector2.zero,
        Breakpoint = self._breakpoint,
        ActiveAnimations = self.Animations:GetActiveCount(),
    }
end

function Nebula:_applyTheme(theme)
    self.Toasts.Theme = theme
end

function Nebula:_applyResponsive()
    if not self._root then return end
    local compact = self._breakpoint == "Compact"
    for _, child in ipairs(self._root:GetChildren()) do
        if child.Name == "NebulaWindow" then
            child.Size = compact and UDim2.new(1, -24, 1, -48) or UDim2.fromOffset(820, 520)
            local navigation = child:FindFirstChild("Navigation")
            local content = child:FindFirstChild("Content")
            if navigation and navigation:IsA("GuiObject") then
                navigation.Visible = not compact
            end
            if content and content:IsA("GuiObject") then
                content.Position = compact and UDim2.fromOffset(16, 78) or UDim2.fromOffset(204, 78)
                content.Size = compact and UDim2.new(1, -32, 1, -98) or UDim2.new(1, -224, 1, -98)
            end
        end
    end
end

function Nebula:Destroy()
    if self._destroyed then
        return
    end
    self._destroyed = true
    self.Maid:Destroy()
end

return Nebula

end

__factories["Rendering.Root"] = function(require)

local Root = {}
Root.__index = Root

local modes = { ["2D"] = true, ["3D"] = true, Hybrid = true }

function Root.new(mode: string?, options: {[string]: any}, maid)
    local self = setmetatable({
        Mode = mode or "2D",
        Options = options or {},
        Instance = nil,
        _maid = maid,
    }, Root)
    self:_create()
    return self
end

function Root:_create()
    if self.Instance and self.Instance.Parent then
        self.Instance:Destroy()
    end
    local playerGui = self.Options.Parent
    local mode = self.Mode
    assert(modes[mode], ("Unsupported Nebula render mode: %s"):format(tostring(mode)))

    local container: Instance
    if mode == "2D" then
        container = Instance.new("ScreenGui")
        container.ResetOnSpawn = false
        container.IgnoreGuiInset = true
        container.DisplayOrder = self.Options.DisplayOrder or 20
        container.Parent = playerGui
    else
        local adornee = self.Options.Adornee
        assert(adornee and adornee:IsA("BasePart"), "3D and Hybrid modes require an Adornee BasePart")
        container = Instance.new("SurfaceGui")
        container.Adornee = adornee
        container.Face = self.Options.Face or Enum.NormalId.Front
        container.SizingMode = Enum.SurfaceGuiSizingMode.PixelsPerStud
        container.PixelsPerStud = self.Options.PixelsPerStud or 50
        container.Parent = adornee
        if mode == "Hybrid" then
            local overlay = Instance.new("ScreenGui")
            overlay.ResetOnSpawn = false
            overlay.IgnoreGuiInset = true
            overlay.DisplayOrder = self.Options.DisplayOrder or 20
            overlay.Parent = playerGui
            self._maid:Give(overlay)
        end
    end
    self.Instance = container
    self._maid:Give(container)
end

function Root:SetMode(mode: string, options: {[string]: any}?)
    assert(modes[mode], ("Unsupported Nebula render mode: %s"):format(tostring(mode)))
    self.Mode = mode
    if options then
        for key, value in pairs(options) do
            self.Options[key] = value
        end
    end
    self:_create()
end

return Root

end

__factories["State.Value"] = function(require)

local Signal = require("Core.Signal")

local Value = {}
Value.__index = Value

function Value.new(initial: any)
    return setmetatable({
        _value = initial,
        _changed = Signal.new(),
        _destroyed = false,
    }, Value)
end

function Value:Get(): any
    return self._value
end

function Value:Set(nextValue: any)
    assert(not self._destroyed, "Cannot set a destroyed Nebula value")
    if self._value == nextValue then
        return
    end
    self._value = nextValue
    self._changed:Fire(nextValue)
end

function Value:Subscribe(callback: (any) -> ()): RBXScriptConnection
    assert(not self._destroyed, "Cannot subscribe to a destroyed Nebula value")
    return self._changed:Connect(callback)
end

function Value:Destroy()
    if self._destroyed then
        return
    end
    self._destroyed = true
    self._changed:Destroy()
end

return Value

end

__factories["Theme.Manager"] = function(require)

local Signal = require("Core.Signal")
local presets = require("Theme.Presets")

local Manager = {}
Manager.__index = Manager

function Manager.new(initial: string?)
    local themes = table.clone(presets)
    local name = initial or "Nebula Dark"
    assert(themes[name], ("Unknown Nebula theme: %s"):format(name))
    return setmetatable({
        _themes = themes,
        _name = name,
        _changed = Signal.new(),
    }, Manager)
end

function Manager:Register(name: string, theme: {[string]: any})
    assert(type(name) == "string" and #name > 0, "Theme name must be a non-empty string")
    assert(type(theme) == "table", "Theme must be a table")
    local merged = table.clone(self._themes["Nebula Dark"])
    for key, value in pairs(theme) do
        assert(merged[key] ~= nil, ("Unknown Nebula theme property: %s"):format(key))
        merged[key] = value
    end
    self._themes[name] = merged
end

function Manager:Set(name: string)
    assert(self._themes[name], ("Unknown Nebula theme: %s"):format(name))
    self._name = name
    self._changed:Fire(self:Get(), name)
end

function Manager:Get(): {[string]: any}
    return self._themes[self._name]
end

function Manager:GetName(): string
    return self._name
end

function Manager:Modify(changes: {[string]: any})
    local current = table.clone(self:Get())
    for key, value in pairs(changes) do
        assert(current[key] ~= nil, ("Unknown Nebula theme property: %s"):format(key))
        current[key] = value
    end
    self._themes[self._name] = current
    self._changed:Fire(current, self._name)
end

function Manager:Reset()
    self:Set("Nebula Dark")
end

function Manager:OnChanged(callback: ({[string]: any}, string) -> ()): RBXScriptConnection
    return self._changed:Connect(callback)
end

function Manager:Destroy()
    self._changed:Destroy()
    table.clear(self._themes)
end

return Manager

end

__factories["Theme.Presets"] = function(require)

local function color(hex: string): Color3
    local value = hex:gsub("#", "")
    return Color3.fromRGB(
        tonumber(value:sub(1, 2), 16) :: number,
        tonumber(value:sub(3, 4), 16) :: number,
        tonumber(value:sub(5, 6), 16) :: number
    )
end

local base = {
    Accent = color("#A995FF"),
    AccentSecondary = color("#5DD5CC"),
    Background = color("#0C1020"),
    BackgroundSecondary = color("#11172B"),
    Surface = color("#171E35"),
    SurfaceSecondary = color("#1D2743"),
    Text = color("#F4F1FF"),
    TextSecondary = color("#B7B9D0"),
    TextMuted = color("#737A9A"),
    Border = color("#303958"),
    BorderHover = color("#6470A0"),
    Success = color("#62D7B5"),
    Warning = color("#F2C977"),
    Error = color("#F47E98"),
    Info = color("#70B6FF"),
    Shadow = color("#050711"),
    CornerRadius = 12,
    BorderThickness = 1,
    Transparency = 0.06,
    Blur = 0,
    AnimationSpeed = 1,
    ControlHeight = 38,
}

local function derive(overrides)
    local result = table.clone(base)
    for key, value in pairs(overrides or {}) do
        result[key] = value
    end
    return result
end

return {
    ["Nebula Dark"] = derive(),
    ["Nebula Light"] = derive({
        Background = color("#EDF1FA"),
        BackgroundSecondary = color("#E2E7F4"),
        Surface = color("#F8F9FD"),
        SurfaceSecondary = color("#E9EDF7"),
        Text = color("#171B2F"),
        TextSecondary = color("#4E5673"),
        TextMuted = color("#7C849F"),
        Border = color("#D4DAEA"),
        BorderHover = color("#9AA6C5"),
        Shadow = color("#8290AC"),
        Transparency = 0,
    }),
    Midnight = derive({ Accent = color("#7397FF"), AccentSecondary = color("#AA7BFF"), Background = color("#070A15") }),
    Graphite = derive({ Accent = color("#D4D9E5"), AccentSecondary = color("#8E9BB5"), Background = color("#101214"), Surface = color("#1D2025") }),
    Aurora = derive({ Accent = color("#6EE7C8"), AccentSecondary = color("#8A8DFF"), Background = color("#0B1520"), Surface = color("#152A35") }),
    Glass = derive({ Accent = color("#8DCAFF"), AccentSecondary = color("#D1B7FF"), Transparency = 0.2, Blur = 8 }),
    Minimal = derive({ Accent = color("#FFFFFF"), AccentSecondary = color("#A7B0C5"), Background = color("#121417"), Surface = color("#1B1E23"), Transparency = 0 }),
}

end

__factories["Utilities.Responsive"] = function(require)

local Responsive = {}

function Responsive.GetBreakpoint(width: number): string
    if width < 600 then
        return "Compact"
    elseif width < 1100 then
        return "Regular"
    end
    return "Wide"
end

function Responsive.TouchTarget(compact: boolean): number
    return compact and 44 or 36
end

return Responsive

end

local __cache = {}

local function __require(name)

    local cached = __cache[name]

    if cached ~= nil then

        return cached

    end

    local factory = __factories[name]

    assert(factory, ("Nebula bundle: module not found: %s"):format(tostring(name)))

    local value = factory(__require)

    __cache[name] = value

    return value

end

return __require("NebulaCore")
